[general]
# The prefix which will act as the suffice of menu links. In other words,
# this makes it easier for phorum to run under a subdirectory like /phorum.
selectorPrefix = "/phorum"
# The maximum length of a post
maximumPostLength = 240
# The number of minutes a user must wait before posting a new thread.
rateLimitMinutesNewThread = 1
# The number of minutes a user must wait before posting a new reply.
rateLimitMinutesNewReply = 1
# The maximum number of replies per thread
maximumRepliesPerThread = 10
# The maximum number of threads
maximumThreads = 10
# The max width used for wrapping infolines when converting blocks of texts into info lines. UNIMPLEMENTED
maxWidth = 50
# How timestamps are displayed
dateFormat = "%Y-%m-%d %H:%M:%S"

[daemon]
port = 7000
name = "localhost"
# Run the daemon as the user below if the daemon was ran as root.
runAsUser = "phorum"

# These codes can be called upon <likeThis> to replace a post message with the content
# below, where between the bracket matches a key in this table. You can add your own keys.
[specialCodes]
# JGS Bear 7/98
jgsBear = '''
        .--. _......._ .--.
       | ( .'         '. ) |
        './  0 _   _ 0  \.'
         |    /  o  \    |
         \    \ _|_ /    /
     jgs  '.__ `"""` __.'
              `"---"`
'''
# JGS: Bag of Money 7/97
jgsBagOfMoney = '''
          \`\/\/\/`/
           )======(
         .'        '.
        /    _||__   \
       /    (_||_     \
      |     __||_)     |
      |       ||       |
      '.              .'
   jgs  '------------
'''

[databaseConnection]
connectHost = "localhost"
connectPort = 5432
connectUser = "your_username"
connectPassword = "your_password"
connectDatabase = "your_database"

[language]
# The text to view an item as a file.
viewAsFile = "View as File"
# The text to view an item as a menu.
viewAsMenu = "View as Menu"
# The text to display when a user was banned for a post.
userWasBannedForThisPost = "USER WAS BANNED FOR THIS POST"
# The text to display to a user as an error when they try to create a thread too frequently.
threadRateLimitExceeded = "Thread post rate limit exceeded."
# The text to display to a user as an error when they try to create a reply too frequently.
replyRateLimitExceeded = "Reply rate limit exceeded."
# The text to display to a user as an error when they try to post and are banned, the text which follows is the actual ban reason/message.
youWereBannedLabel = "You were banned. Reason: "
# Ambiguous error/post insertion failure.
failedToInsertPost = "Failed to insert post."
# Text to display when successfully delted a thread by id (the actual post ID will follow).
deletedThreadWithId = "Deleted thread with ID: "
# The text to display upon successfully unbanning an IPv6 address.
ipUnbannedSuccess = "IP unbanned successfully: "
# If trying to ban a post and the post is not found or the IP is missing, this is the error message.
postNotFoundOrIpMissing = "Post not found or IP missing."
# The success message for adding a given IPv6 address to the ban list. Following is the actual IP address.
ipBannedSuccessfully = "IP banned successfully: "
# The text/link/query item for for replying to a thread.
threadReply = "Reply to Thread"
# The text for the directory item that links back to the index view.
returnToIndex = "Return to Index"
# The text for the index search item used to creating a new thread.
createThread = "Create Thread"
threadIndexOpNumberLabel = "No. "
singleReplyOmitted = "1 reply omitted, view thread to see it."
# In the index view a threads replies are omitted from the view if there's more than `n`.
pluralRepliesOmitted = " replies omitted, view thread to see them all."
# Client sent an empty string for a post.
postEmpty = "Client sent an empty query."
# User attempts to create a post that's too long.
postTooLong = "Post is too long. Maximum length is %d characters. Your post was %d characters."
# Same IP makes a reply to a thread, where the latest reply has the same IP and contents
spamReplyError = "I think you made this reply already (same IP and contents as latest reply in this thread). It may be because you tried refreshing an index search result."
# Duplicate thread error
sameThreadError = "A thread with the text contents you provided already exists."

[fileViews]
# Thread view settings
threadOpBorderHorizontal = "="
threadOpBorderVertical = "#"
threadOpBorderCorner = "@"
threadOpMinimumWidth = 40
threadOpMaximumWidth = 69
threadOpPadding = 2
threadReplyBorderHorizontal = "-"
threadReplyBorderVertical = "|"
threadReplyBorderCorner = "+"
threadReplyMinimumWidth = 40
threadReplyMaximumWidth = 69
threadReplyPadding = 2

[menuViews]
# Index view settings
indexReplyLeadingBreak = true
indexReplyTrailingBreak = false
# The left side of the heading for the original post in the index view.
indexOpHeadingDecorLeft = "### "
# The right side of the heading for the original post in the index view.
indexOpHeadingDecorRight = " ###"
# The threshold for the number of replies in a thread before they are omitted from the index view.
ommittedRepliesThreshold = 3
# Feel free to use \n! Use ASCII art or whatever! Displayed at the top of the thread index.
indexPreamble = "Welcome to the Gopher Den!"
# The left side of the heading for a reply in a thread view.
indexReplyHeadingDecorLeft = "* "
# The right side of the heading for a reply in a thread view.
indexReplyHeadingDecorRight = ""
# The left side of the heading for the original post in a thread view.
threadOpHeadingDecorLeft = "### "
# The right side of the heading for the original post in a thread view.
threadOpHeadingDecorRight = " ###"
# The label for the thread number in a thread view.
threadOpThreadNumberLabel = "Viewing Thread #"
threadReplyNumberLabel = "Reply #"
threadReplyHeadingDecorLeft = "---"
